### PR TITLE
Chore: deletion of unnecessary BankApp folder

### PR DESCRIPTION
**Pull request by perry-C**
Additionally I also added a .gitignore file to the commit, although **I can not figure out why it still commits some environmental/binary files to git**

### CODE REVIEW

**Review by khadir786 — APPROVED** [review]

**Review by Wilsonator123 — APPROVED** [review]

**Comment by Wilsonator123** [comment]
You don't need to wait for everyone to approve. As long as someone approves you should be fine @perry-C

**Review by Josephaguele — COMMENTED** [review]
Looks good to me Pai, please after you tested the app after the changes you made ? @perry-C

**Comment by perry-C** [comment]
> You don't need to wait for everyone to approve. As long as someone approves you should be fine @perry-C  

Got it

**Comment by perry-C** [comment]
> Looks good to me Pai, please after you tested the app after the changes you made ? @perry-C 

Yes I have, then again it shouldn't affect anything since I have not modified anything important

**Comment by Josephaguele** [comment]
thanks Pai

**Pull request merged**
